@startuml example-nodes

usecase "x" as x

usecase "a = sin(x)" as a
a ..> x

usecase "b = cos(y)" as b
b ..> x

usecase "c = x a" as c
c ..> x
c ..> a

usecase "y = b c" as y
y ..> b
y ..> c

@enduml
